### PR TITLE
pulling request?

### PR DESCRIPTION
**Pull request by hassan-oldover**
how to pulling? makes project better? thanks

### CODE REVIEW

**Comment by hassan-oldover** [comment]
making change to access write? thanks

**Comment by hassan-oldover** [comment]
hi?

**Comment by hassan-oldover** [comment]
...?

**Comment by hassan-oldover** [comment]
derogoldncoin dies? or dev response? we make better with us

**Comment by zpalmtree** [comment]
crappy pls go

**Pull request closed without merging**
