### PR TITLE
Increase block times from 10->20, increase emission from 23->24

### PR DESCRIPTION
**Pull request by zpalmtree**
This gives an effective decrease in rewards of 4x.

Effective at 650k.

### CODE REVIEW

**Comment by zpalmtree** [comment]
Any objections or anyone want to review? I'll merge in tomorrow if not.

**Comment by wrkzdev** [comment]
No objection :)

**Comment by MaayanSG** [comment]
No objection! I’m officially on team20s

**Comment by bobbieltd** [comment]
This fork won’t solve the real issue. 20s is still short. If you still want to use 20s, I think you should change diff ago to make it less crazy.

**Comment by zpalmtree** [comment]
I personally would go with a slower block time than 20 seconds, but it's more up to the community than me. LWMA-2 has worked well on a lot of coins, and I have no issue with it, what is your concern with the diff algo?

**Comment by bearybullish** [comment]
Agree, 20 seconds is an improvement over 10, but there might be a better number.

**Comment by bobbieltd** [comment]
I do not have knowledge about blockchain and Zawy’s diff algo.
Swap’s 15 seconds and Dero’s 12 work very well. My personal assumptions about the cause : 1. Turtlecoin codebase has sync issue in the root —> necessary improvement, 2. Diff algo : Zawy algo works well with high block time but it exaggerates chain splitting and sync.

If short block time is your coin’s feature, it is better to keep 10s (well, DeroGold is better because of having shorter block time than Dero and other coins).
If not, block time should be > 60s to have better sync. I got sync issue with 30s/60s coins.
Block propagation needs 2s + 0.08s per kB (Google). Perhaps to maintain short block time, you should reduce max block size. Smaller block size won’t cause much issue if in the future we can improve txes size (for example bulletproof).
For diff part, perhaps Zawy algo is good, I’m not sure if downing diff correction causes more split chains or not.
Database “corruption” happens with Turtlecoin too when there are many split chains (see Miners.rock issue). I don’t see much diffrence between 20s and 10s. Less problem but there is still problem.
Final point, if you prefer 20s, I prefer 10s. If not, I suggest > 40s.

**Comment by netmebtc** [comment]
Most of the community members who favor 20s to 10s are the owners of those small pools and some people who run node nodes. The main problem is that 10s is too easy to appear orhand, and daemon often restarts or file corruption, as bobbieltd said , these problems will also appear in Trtl. Who can guarantee that these problems will not occur in 20s?Although there are such problems, we have seen that there is no abnormal reduction in the hash rate of the whole network, which is always keep at 2Mh/s~3Mh/s, and most of the pools can work normally.I know that the miners are willing to dig this DEGO, that is they like blocks that appear at such a fast speed as 10s. If the number of degos produced per day becomes less after 20s, the miners’ interest in mining may be reduced, so please ask the community think carefully, if it becomes 20s, the hashrate may be reduced, like many altcoins now, and gradually forgotten.

**Comment by netmebtc** [comment]
I like this opinion :   " it is better to keep 10s (well, DeroGold is better because of having shorter block time than Dero and other coins). "   DeroGold is better than Dero,It sounds very exciting

**Comment by netmebtc** [comment]
A terrible fairy tale:：   Hi george, why are you looked so sad?.... Well, because the block speed of DEGO is going to be a terrible 20s.....  What, are they crazy? Do they want to kill DeroGold? ......Yes, I don't know what to do next....... Oh, poor George, I'll tell you a way. After they upgrade 20S, you can take Derogold fork to DeroDiamand (DERD), keep 10s, and surpass them... Hahaha, you're a genius. That's a good idea. I believe the miners like DERD better...

**Comment by bobbieltd** [comment]
What netmebtc says is right. Forking to 20s is to kill the coin and solves nothing. Sync problem will be still there. 
DeroGold from one of the fastest coin on earth becomes nothing coin.

**Comment by zpalmtree** [comment]
Well, maybe we could put it to a vote. The numbers are easy to change now the surrounding code is written.

**Comment by bobbieltd** [comment]
Doing a vote is good method but many people still think that 20s will fix the sync issue. Votes will be quite biased. At least, you or the team should give better information about this fork. It probably will resolve nothing.

**Comment by zpalmtree** [comment]
I don't know exactly what you refer to as the sync issue. Fast block times just a larger chain, nothing more.

**Comment by bobbieltd** [comment]
Perhaps, sync issue is my imagination. 
I like your hard work and thank you.
It needs many opinions to be considered. I already gave mine (it could be right or wrong, just personal opinions).

**Comment by rogerrobers** [comment]
Fork to 20 and 24 was discussed and pushed back to 700k

**Pull request merged**
