### PR TITLE
DeroGold no-bin files

### PR DESCRIPTION
**Pull request by wrkzdev**
### REMARK: **Not merge yet until further tests passed and some code needs more commits**
Idea: https://github.com/turtlecoin/turtlecoin/pull/1033 and https://github.com/wrkzcoin/wrkzcoin/pull/41, it's easy to make a track here and update.

#### Tested before PR
I have done a very basic test only synced up to block 1221 from 0 and do some basic test below:
* Daemon is sync'ing with DeroGold Network as normal without bin files
* Export / Import to and from **blockchain.dump** is working with my test height 1221

#### Daemon to further test (RocksDB and LevelDB)
* Sync from 0 to top height
* Sync from existing database
* Import / Export to dump file to 2,350,00 (TBC)

#### Wallet to test
* zedwallet-beta import, send tx, fusion tx
* wallet-service import, send tx, fusion tx
* wallet-api import, send tx, fusion tx

#### Note
I have removed zedwallet inside this PR.

#### Log before PR
* **Export**
Progress [1 / 1221] @ Time [20:50:44]
Progress [1221 / 1221] @ Time [20:50:45]
Time to export 0 seconds.

* **Import**
2020-Oct-04 20:51:14.653750 INFO    Initializing core...
2020-Oct-04 20:51:14.663724 INFO    Core initialized OK
2020-Oct-04 20:51:14.667720 INFO    Importing blockchain...
Existing DB has currentIndex: 1
Importing block [1] @ Time [20:51:14]
Importing block [1000] @ Time [20:51:19]
Completed at block 1221
Time to import 8 seconds.

### CODE REVIEW

**Comment by wrkzdev** [comment]
```
-------------------------------------------
| Local Height            | 2377251       |
| Network Height          | 2377251       |
| Percentage Synced       | 100.00%       |
| Network Hashrate        | 75.84 KH/s    |
| Block Version           | v6            |
| Incoming Connections    | 13            |
| Outgoing Connections    | 0             |
| Uptime                  | 0d 0h 18m 54s |
| Fork Status             | Up To Date    |
| Next Fork               | 51.56 Days    |
| Transaction Pool Size   | 14            |
| Alternative Block Count | 0             |
| DB Engine               | RocksDB       |
| Version                 | 0.5.1.1       |
-------------------------------------------
```
Crashed 3 times with RocksDB + ZSTD. I think there should not be crash with LevelDB.
```
RocksDB size up-to-date:  285G  (data/DB)
```

**Comment by wrkzdev** [comment]
#### Dump successfully with 3 crashes for RocksDB + ZSTD (4GB RAM):
* DeroGold blockchain dump file: https://dego-data-dir.bot.tips/update_20201009/blockchain.dump 
* Export logs:
```
Progress [2280001 / 2377000] @ Time [11:37:38]
Progress [2304001 / 2377000] @ Time [11:37:44]
Progress [2328001 / 2377000] @ Time [11:37:49]
Progress [2352001 / 2377000] @ Time [11:38:58]
Progress [2376001 / 2377000] @ Time [11:39:34]
Progress [2377000 / 2377000] @ Time [11:39:40]
Time to export 1184 seconds.
```
* sha1sum blockchain.dump
```fb5e70ff27f2feb43765ad6645430091143ef1dd  blockchain.dump```

* If anyone want to try out the import this dump file, give a try to binary from this current PR:
https://dego-data-dir.bot.tips/update_20201009/binary/

**Comment by wrkzdev** [comment]
#### LevelDB finally sync'ed:
```
--------------------------------------------
| Local Height            | 2379534        |
| Network Height          | 2379534        |
| Percentage Synced       | 100.00%        |
| Network Hashrate        | 122.85 KH/s    |
| Block Version           | v6             |
| Incoming Connections    | 12             |
| Outgoing Connections    | 0              |
| Uptime                  | 0d 20h 17m 12s |
| Fork Status             | Up To Date     |
| Next Fork               | 51.03 Days     |
| Transaction Pool Size   | 43             |
| Alternative Block Count | 0              |
| DB Engine               | LevelDB        |
| Version                 | 0.5.1.1        |
--------------------------------------------
```

Crashed 3 times also but not from OOM.

```
460G    data/LevelDB
```

**Comment by wrkzdev** [comment]
#### New blockchain dump file the same as RocksDB version. This was running in a smaller cloud VPS (3vCPU - 4GB RAM) different system from previous run. Swap needs to be added 4GB extra, otherwise it crashes after 2 million blocks.

```
./DeroGoldd --data-dir=./data --db-enable-level-db --export-blockchain --max-export-blocks 2377000
....
Progress [2322001 / 2377000] @ Time [02:24:56]
Progress [2325001 / 2377000] @ Time [02:25:15]
Progress [2328001 / 2377000] @ Time [02:25:23]
Killed
```

### dump LevelDB
```
./DeroGoldd --data-dir=./data --db-enable-level-db --export-blockchain --max-export-blocks 2377000

Progress [2340001 / 2377000] @ Time [04:36:13]
Progress [2343001 / 2377000] @ Time [04:36:15]
Progress [2346001 / 2377000] @ Time [04:36:29]
Progress [2349001 / 2377000] @ Time [04:36:43]
Progress [2352001 / 2377000] @ Time [04:36:49]
Progress [2355001 / 2377000] @ Time [04:36:57]
Progress [2358001 / 2377000] @ Time [04:36:57]
Progress [2361001 / 2377000] @ Time [04:37:03]
Progress [2364001 / 2377000] @ Time [04:37:13]
Progress [2367001 / 2377000] @ Time [04:37:51]
Progress [2370001 / 2377000] @ Time [04:37:53]
Progress [2373001 / 2377000] @ Time [04:38:04]
Progress [2376001 / 2377000] @ Time [04:38:33]
Progress [2377000 / 2377000] @ Time [04:39:09]
Time to export 6978 seconds.

sha1sum blockchain.dump
fb5e70ff27f2feb43765ad6645430091143ef1dd  blockchain.dump
```

**Comment by wrkzdev** [comment]
I proposed the write buffer:
```
    const uint64_t ROCKSDB_WRITE_BUFFER_MB = 4; // 4 MB
..
    const uint64_t LEVELDB_WRITE_BUFFER_MB = 4; // 4 MB
```

That is to avoid many unsaved blocks caused by daemon crashes or improper shutdown.

**Comment by LeoStehlik** [comment]
I think I’d prefer bigger write buffer as they help when network is busy with transactions. I know there’s a downside if unclean shutdown of the daemon happens, however, due to the improved stability of the daemon with LevelDB, I’d say this is an acceptable trade-off.

**Pull request merged**
